sudo: required
services:
        - docker
before_install:
        - docker build -t carlbolger/react-test -f ./client/Dockerfile.dev ./client

script:
        - docker run carlbolger/react-test npm test -- --coverage

after_success:
        - docker build -t carlbolger/multi-client ./client
        - docker build -t carlbolger/multi-server ./server
        - docker build -t carlbolger/multi-nginx ./nginx
        - docker build -t carlbolger/multi-worker ./worker
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        - docker push carlbolger/multi-client
        - docker push carlbolger/multi-server
        - docker push carlbolger/multi-nginx
        - docker push carlbolger/multi-worker

deploy:
        provider: elasticbeanstalk
        region: us-east-2
        app: multi-docker
        env: MultiDocker-env
        bucket_name: elasticbeanstalk-us-east-2-487999195629
        bucket_path: docker-multi
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key:
                secure: $AWS_SECRET_KEY
